BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Boss Dog Brewery', '2163212337', 'www.bossdogbrewing.com','2179 Lee Road', 'Cleveland Heights', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('BrewNuts', '2164718008', 'www.brewnutscleveland.com', '6501 Detroit Avenue','Cleveland', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Fat Heads Brewery', '2168980242', 'www.fatheads.com', '17450 Engle Lake Drive', 'Middleburg Heights', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Great Lakes Brewing', '2167714404', 'www.greatlakesbrewing.com', '2516 Market Ave', 'Cleveland', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Hoppin Frog Brewery', '3303524578', 'www.hoppinfrog.com', '2572 Scraton Road', 'Cleveland', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Market Garden Brewery', '2166214000', 'www.marketgardenbrewery.com', '1947 W 25TH Street', 'Cleveland', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Moosehead Saloon', '4408717742', 'www.mooseheadrestaurant.com', '694 Dover Center Road', 'Westlake', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Sibling Revelry Brewery', '4404718589', 'www.siblingrevelrybrewing.com', '29305 Clemens Road', 'Westlake', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Thirsty Dog Brewery', '3302522739', 'www.thirstydog.com', '1075 Old River Road', 'Cleveland', 'Ohio');
INSERT INTO breweries (name, phone, url, street, city, state) VALUES ('Wolfs Ridge Brewing', '6144293936', 'www.wolfsridgebrewing.com', '215 N 4th Street', 'Columbus', 'Ohio');

INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Guinness', 'The Irish dry stout originated in Dublin in 1759. The dark and thick brew is hugely popular in the United Kingdom and Ireland, naturally. The brew’s popularity is eclipsed in only one other country: Nigeria, where Smithsonian Magazine reports there are more Guinness drinkers than in all of Ireland.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-1073457242.jpg?resize=876,584', '4.2', 'Stout');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Heineken', 'This pale lager originated in the Netherlands in 1873 and has appeared as product placement in seven “James Bond” franchise movies and many advertisements, including “Daniel Craig vs. James Bond” for the latest installment, “No Time to Die.”', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-948909884.jpg?resize=876,584', '5.4', 'Pale Lager');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Corona', 'The company behind this Mexican pale lager said Corona’s unfortunate name similarity to the coronavirus didn’t negatively impact its sales.', 'https://thehill.com/wp-content/uploads/sites/2/2020/04/ca_coronabeer_040320istock.jpg?resize=876,535', '4.6','Mexican Pale Lager');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Samuel Adams', 'Often called “Sam Adams,” this lager is named after one of America’s founding fathers. It was introduced in 1984. Last year, Samuel Adams launched a limited edition beer so strong it was illegal to sell in 15 states.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-1148287453.jpg?resize=876,672', '5.0', 'Lager');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Budweiser', 'This pale lager was first sold in 1876 in St. Louis, Missouri. Since its introduction, the Anheuser-Busch-owned Budweiser has faced several trademark disputes with the European company Budweiser Budvar. That company owns the rights to the Budweiser name overseas. Budweiser is also known for many of its iconic Super Bowl ads.', 'https://thehill.com/wp-content/uploads/sites/2/2018/05/beer_cans_1.jpg?resize=876,492', '5.0', 'Pale Lager');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Miller High Life', 'Also known as Miller High Life, Miller, a pilsner-style beer, is the company’s oldest brand. It bills itself as “the Champagne of Beers.” The company has even taken the slogan so far as producing the beer in champagne bottles as part of a holiday edition.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-455488292.jpg?resize=876,584', '4.6', 'Pilsner Style');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Blue Moon', 'This Belgian-style beer was originally called “Bellyslide Wit” when it was launched in 1995 at the Sandlot Brewery in Denver, Colorado.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-614940960.jpg?resize=876,584', '5.4', 'Belgian Style');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Stella Artois', 'The Belgium-originated pilsner was originally created as a Christmas season beer and it’s even named after the Star of Bethlehem, or the Christmas Star. Statistica data updated last year showed Stella Artois as the UK’s top beer based on consumer favorability.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-1014169172.jpg?resize=876,582', '5.2', 'Belgian Style');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Bud Light', 'Budweiser’s light beer was first introduced in 1982 and is known by its cobalt blue labeling. Data by the Beer Marketer’s Insights in 2019 reviewed shipping numbers, which determined (based on how much is shipped to retailers), Bud Light is America’s most popular beer brand.', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/GettyImages-1005678174.jpg?resize=876,584', '5.0', 'Light Lager');
INSERT INTO beers (beer_name, beer_description, image, abv, beer_type) VALUES ('Dos Equis ', 'The green-bottled Mexican lager with the double-X name comes in at number 10. It’s known for its now-retired spokesperson, the so-called “Most Interesting Man in the World.”', 'https://thehill.com/wp-content/uploads/sites/2/2022/07/AP995939668061.jpg?resize=876,584', '4.2', 'Mexican Lager');


COMMIT TRANSACTION;
